-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0nfq59xaiJwNV0kU
qQysPvmrjFEDcQDnAiNGECtiJv6gCgYIKoZIzj0DAQehRANCAATHE60Ew+Te/eJw
IXXIpAGa4zhvh8N8FrWUinbLSATJWzd/L9ITXhZJoNxqmjRjXN6iedeFKLfSokLJ
6SmAcPWY
-----END PRIVATE KEY-----